-- =============================================================================
-- CareConnect: Patient-Provider EHR (Electronic Health Record System)
-- Oracle XE Database Schema & Seed Data Script
-- Compatible with Oracle Database 10g, 11g, 18c, 19c, 21c, 23c XE
-- =============================================================================

-- 1. USERS & RBAC TABLE
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(60) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    full_name VARCHAR2(120) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    role VARCHAR2(25) NOT NULL,
    patient_id NUMBER,
    specialization VARCHAR2(100),
    license_number VARCHAR2(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 2. PATIENT MASTER INDEX (EMPI) TABLE
CREATE TABLE patients (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mrn VARCHAR2(30) NOT NULL UNIQUE,
    first_name VARCHAR2(60) NOT NULL,
    last_name VARCHAR2(60) NOT NULL,
    date_of_birth DATE NOT NULL,
    gender VARCHAR2(15) NOT NULL,
    blood_group VARCHAR2(5),
    phone VARCHAR2(20),
    email VARCHAR2(100),
    address VARCHAR2(250),
    city VARCHAR2(50),
    state VARCHAR2(50),
    postal_code VARCHAR2(20),
    emergency_contact_name VARCHAR2(100),
    emergency_contact_phone VARCHAR2(20),
    emergency_contact_relationship VARCHAR2(50),
    allergies VARCHAR2(500),
    chronic_conditions VARCHAR2(500),
    insurance_provider VARCHAR2(100),
    policy_number VARCHAR2(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. VITALS FLOWSHEET TABLE
CREATE TABLE vital_signs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id NUMBER NOT NULL,
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    systolic_bp NUMBER(3),
    diastolic_bp NUMBER(3),
    heart_rate NUMBER(3),
    respiratory_rate NUMBER(3),
    temperature NUMBER(4, 1),
    oxygen_saturation NUMBER(3),
    height_cm NUMBER(5, 1),
    weight_kg NUMBER(5, 1),
    bmi NUMBER(4, 1),
    recorded_by VARCHAR2(100),
    notes VARCHAR2(255),
    CONSTRAINT fk_vital_patient FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE
);

-- 4. CLINICAL DOCUMENTATION & SOAP NOTES TABLE
CREATE TABLE clinical_encounters (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id NUMBER NOT NULL,
    provider_id NUMBER NOT NULL,
    provider_name VARCHAR2(120) NOT NULL,
    encounter_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    encounter_type VARCHAR2(30) NOT NULL,
    chief_complaint VARCHAR2(250) NOT NULL,
    soap_subjective CLOB,
    soap_objective CLOB,
    soap_assessment CLOB,
    soap_plan CLOB,
    icd10_codes VARCHAR2(200),
    status VARCHAR2(20) DEFAULT 'COMPLETED' NOT NULL,
    signed_at TIMESTAMP,
    signed_by VARCHAR2(120),
    CONSTRAINT fk_enc_patient FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE
);

-- 5. CPOE (COMPUTERIZED PHYSICIAN ORDER ENTRY) TABLE
CREATE TABLE medical_orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id NUMBER NOT NULL,
    provider_id NUMBER NOT NULL,
    encounter_id NUMBER,
    order_type VARCHAR2(30) NOT NULL,
    order_name VARCHAR2(150) NOT NULL,
    loinc_code VARCHAR2(30),
    priority VARCHAR2(20) NOT NULL,
    clinical_indication VARCHAR2(500),
    status VARCHAR2(25) DEFAULT 'PENDING' NOT NULL,
    ordered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    result_notes CLOB,
    normal_range VARCHAR2(100),
    flagged_abnormal NUMBER(1) DEFAULT 0,
    CONSTRAINT fk_order_patient FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE
);

-- 6. MEDICATION & E-PRESCRIPTIONS TABLE
CREATE TABLE prescriptions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id NUMBER NOT NULL,
    provider_id NUMBER NOT NULL,
    encounter_id NUMBER,
    medication_name VARCHAR2(150) NOT NULL,
    rx_norm_code VARCHAR2(30),
    dosage VARCHAR2(50) NOT NULL,
    frequency VARCHAR2(50) NOT NULL,
    route VARCHAR2(30) NOT NULL,
    duration_days NUMBER(4),
    instructions VARCHAR2(250),
    refills NUMBER(2) DEFAULT 0,
    status VARCHAR2(25) DEFAULT 'ACTIVE' NOT NULL,
    prescribed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_rx_patient FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE
);

-- 7. DRUG-DRUG INTERACTION RULES TABLE
CREATE TABLE drug_interactions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drug_a VARCHAR2(100) NOT NULL,
    drug_b VARCHAR2(100) NOT NULL,
    severity VARCHAR2(20) NOT NULL,
    description VARCHAR2(500) NOT NULL,
    clinical_recommendation VARCHAR2(500)
);

-- 8. HIPAA AUDIT LOG TABLE
CREATE TABLE audit_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    performed_by VARCHAR2(60) NOT NULL,
    user_role VARCHAR2(30),
    action VARCHAR2(50) NOT NULL,
    entity_name VARCHAR2(50) NOT NULL,
    entity_id NUMBER,
    details VARCHAR2(1000),
    ip_address VARCHAR2(45)
);

-- Seed Initial Drug-Drug Interactions
INSERT INTO drug_interactions (drug_a, drug_b, severity, description, clinical_recommendation)
VALUES ('Warfarin', 'Aspirin', 'HIGH',
        'Concurrent use significantly increases risk of major gastrointestinal and systemic bleeding.',
        'Avoid combination unless specifically indicated; close INR monitoring mandatory.');

INSERT INTO drug_interactions (drug_a, drug_b, severity, description, clinical_recommendation)
VALUES ('Lisinopril', 'Spironolactone', 'HIGH',
        'Concurrent ACE inhibitor and potassium-sparing diuretic can cause severe, life-threatening hyperkalemia.',
        'Monitor serum potassium and renal function within 1 week of co-administration.');

INSERT INTO drug_interactions (drug_a, drug_b, severity, description, clinical_recommendation)
VALUES ('Metformin', 'Iodinated Contrast', 'HIGH',
        'Risk of lactic acidosis in patients undergoing radiographic procedures with iodinated contrast media.',
        'Discontinue metformin prior to procedure; withhold for 48 hours post-procedure until normal renal status confirmed.');

COMMIT;
